// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	AddOffice(ctx context.Context, arg AddOfficeParams) (Office, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreateHQOffice(ctx context.Context, name string) (Office, error)
	CreateOfficeCurrency(ctx context.Context, arg CreateOfficeCurrencyParams) (OfficeCurrency, error)
	CreateOfficeCurrencyRate(ctx context.Context, arg CreateOfficeCurrencyRateParams) (OfficeCurrencyRate, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteCurrency(ctx context.Context, id int64) error
	DeleteOfficeCurrency(ctx context.Context, id int64) error
	DeleteOfficeCurrencyRate(ctx context.Context, id int64) error
	DeleteTransaction(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetCurrency(ctx context.Context, id int64) (Currency, error)
	GetOffice(ctx context.Context, id int64) (Office, error)
	GetOfficeCurrency(ctx context.Context, id int64) (OfficeCurrency, error)
	GetOfficeCurrencyRate(ctx context.Context, id int64) (OfficeCurrencyRate, error)
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListAccount(ctx context.Context, arg ListAccountParams) ([]Account, error)
	ListCurrency(ctx context.Context, arg ListCurrencyParams) ([]Currency, error)
	ListOffice(ctx context.Context, arg ListOfficeParams) ([]Office, error)
	ListOfficeCurrency(ctx context.Context, officeID int64) ([]OfficeCurrency, error)
	ListOfficeCurrencyRate(ctx context.Context, arg ListOfficeCurrencyRateParams) ([]OfficeCurrencyRate, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error)
	UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (Office, error)
	UpdateOfficeCurrencyRate(ctx context.Context, arg UpdateOfficeCurrencyRateParams) (OfficeCurrencyRate, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
